name: Maven Run Tests when push to Main branch and newly created PRs.

on:
  # Trigger the workflow on push for the main branch
  # and pull request for main and card-* prefix branches
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Build with Maven
        run: mvn clean install